site_name: LinguoBook
site_description: Intelligent book reader with word translate feature
site_author: Yehor Horin

theme:
  name: material
  favicon: assets/logo.png   
  logo: assets/logo.png
  font:
    text: Merriweather
    code: Fira Code
  palette:
    primary: custom
    accent: custom
  features:
    - navigation.tabs
    - navigation.top

extra_css:
  - stylesheets/book_theme.css

nav:
  - Main page: index.md
  - Privacy policy: policy.md
  - Terms of use: terms.md
  - Support: support.md

markdown_extensions:
  - md_in_html