site_name: LinguoBook
site_description: Intelligent book reader with word translate feature
site_author: Yehor Horin

theme:
  name: material
  palette:
    primary: indigo
    accent: blue
  features:
    - navigation.tabs

nav:
  - Main page: index.md
  - Privacy policy: policy.md
  - Terms of use: terms.md

markdown_extensions:
  - md_in_html